# Generated by Django 6.0.7 on 2026-07-23 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL Slug')),
                ('icon', models.CharField(blank=True, help_text='Masalan: bi bi-laptop', max_length=50, verbose_name='FontAwesome/Bootstrap Ikonka sinfi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Kategoriya rasmi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Ota kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="E'lon sarlavhasi")),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Narxi (so'm)")),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='Kelishtiriladi')),
                ('condition', models.CharField(choices=[('NEW', 'Yangi'), ('USED', 'Ishlatilgan'), ('REFURBISHED', 'Tiklangani (Refurbished)')], default='USED', max_length=20, verbose_name='Holati')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING', 'Tekshiruvda (Moderatsiya)'), ('ACTIVE', 'Faol'), ('REJECTED', 'Radd etilgan'), ('SOLD', 'Sotilgan')], default='PENDING', max_length=20, verbose_name="E'lon holati")),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('city', models.CharField(max_length=100, verbose_name='Tuman / Shahar')),
                ('is_vip', models.BooleanField(default=False, verbose_name="VIP e'lon")),
                ('is_top', models.BooleanField(default=False, verbose_name="TOP e'lon")),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Kategoriya')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name': "Mahsulot / E'lon",
                'verbose_name_plural': "Mahsulotlar va E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Rasm')),
                ('is_main', models.BooleanField(default=False, verbose_name='Asosiy rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
            },
        ),
    ]
