# Generated by Django 5.2.16 on 2026-07-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Masalan: +998901234567', max_length=20, null=True, verbose_name='Aloqa uchun tel. raqam'),
        ),
    ]
