# Generated by Django 5.2.16 on 2026-08-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('SOLD', 'Sotilgan')], default='ACTIVE', max_length=20, verbose_name="E'lon holati"),
        ),
    ]
